### ISSUE TITLE
8 nodes no leader 

### ISSUE THREAD

**Issue by YuehChuan** [42dot/foros#2]
The demo works charm for me! Great!
But, when I set the numbers of nodes to 8, and kill each leader one by one;  When the number of nodes is equal
and less then 4 nodes, there will be no Leader but only candidates and followers remain.
Any idea?
Take a look!
Screencast!
https://1drv.ms/v/s!AsLam7iob4O7m2KJTwURRylR6Dsj?e=cfv7nz

**Comment by huchijwk** [comment]
This is the correct behavior.

RAFT algorithm can tolerate failures equal to the cluster size minus the quorum.
(* quorum = cluster size / 2 + 1)
This means that more than half of the nodes in the cluster are required to reach consensus.

In your example, the cluster size is 8 and the quorum is 5.
Therefore, at least 5 nodes are required to reach consensus.

screenshot of README.md
![image](https://user-images.githubusercontent.com/31328739/199669583-e74da833-dc84-40bc-8393-efa601663c64.png)

**Comment by YuehChuan** [comment]
> This is the correct behavior.
> 
> RAFT algorithm can tolerate failures equal to the cluster size minus the quorum. (* quorum = cluster size / 2 + 1) This means that more than half of the nodes in the cluster are required to reach consensus.
> 
> In your example, the cluster size is 8 and the quorum is 5. Therefore, at least 5 nodes are required to reach consensus.
> 
> screenshot of README.md ![image](https://user-images.githubusercontent.com/31328739/199669583-e74da833-dc84-40bc-8393-efa601663c64.png)

Thanks for the explanation!
I will check it!
